variables:
  # Name of your Azure DevOps service connection to your AML workspace
  ml_workspace_connection: 'aml-workspace-connection'

  # Name of your AML workspace and its resource group
  ml_workspace_name: 'csamlfsi-ws'
  ml_workspace_rg: 'csamlfsi-rg'

  # Name of your Compute Cluster (needs to exist)
  ml_compute_name: 'cpu-cluster2'

  # Name of your experiment for training tracking
  ml_experiment_name: 'aml-prod-ci'

  # Model name for registration and its path in the repo
  ml_model_name: 'aml-demo-model-prod'
  ml_model_path: 'models/aml-demo'

  # Desired model output name
  ml_model_filename: 'aml-demo-model.pkl'

  # AKS cluster to deploy to (needs to exist)
  ml_aks_cluster: 'aks-prod'

  # Model deployment name
  ml_deployment_name: 'aml-demo-deployment-prod'